language: python
sudo: yes
python:
  - 3.6
before_install:
  - sudo add-apt-repository ppa:maarten-fonville/protobuf -y
  - sudo apt-get update -q
  - sudo apt-get install protobuf-compiler
install:
  - pip install sphinx sphinx_rtd_theme javasphinx upstream/rsb-python
script:
  - ./build.sh
